#!/bin/bash
if [ -f /tmp/file1.txt ] 2> /dev/null
then
        cd /var/www/html/ 
        sudo  sed  's/Task1. Incorrect/Task1. Correct/' index.html -i
        sudo  sed   -e 's|Task1. 0|Task1. 1|g' index.html -i
else
        :
fi
